# Generated by Django 5.1.1 on 2024-10-09 21:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pedidos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('open', 'open'), ('canceled', 'Canceled'), ('paid', 'Paid')], default='open', max_length=10)),
                ('date_create', models.DateField(auto_now_add=True, verbose_name='created date')),
                ('total_preco', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='total preco')),
            ],
            options={
                'db_table': 'pedidos',
            },
        ),
        migrations.CreateModel(
            name='PedidosItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preco', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='preco')),
                ('quantidade', models.IntegerField(default=1, verbose_name='quantidade')),
                ('pedidos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pedidos_items', to='pedidos.pedidos')),
            ],
            options={
                'db_table': 'pedidos_item',
            },
        ),
    ]
