# Generated by Django 5.1.1 on 2024-09-05 00:25

import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categorias', '0003_alter_category_name_category_unique_category_name'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='category',
            name='unique_category_name',
        ),
        migrations.AddConstraint(
            model_name='category',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('name'), name='Categoria ja Existente'),
        ),
    ]
