# Generated by Django 5.1.1 on 2024-10-09 23:07

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tables',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_reservation', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('free', 'Free'), ('busy', 'Busy')], default='free', max_length=4)),
                ('date_end', models.DateTimeField()),
            ],
        ),
    ]
